# Analytical Base Table -- Build & Descriptive Profile

Merged from `Analytical_Base_Table.ipynb` (builds the ABT from the three raw
CSVs) and `ABT_Descriptive.ipynb` (profiles it). The descriptive section now
runs directly against the table just built in memory, instead of re-reading
`Group2_ABT.csv` from disk -- that file is never produced by the build
section, so the two notebooks couldn't previously be run back-to-back
without it existing already from somewhere else. See the chat reply below
this for why, and what to check if `Group2_ABT.csv` is actually a distinct,
further-processed file you still need elsewhere.

## Path setup (added)

Defines the data directory once, matching this notebook's location (two
folders below the project root, same convention as the original
`../../data/...` paths).

In [1]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[1]  # two levels up, matching this notebook's location
DATA_DIR = PROJECT_ROOT / "data"

## **Imports & Loading CSV**

In [2]:
import pandas as pd

air_quality_path = str(DATA_DIR / "ph_air_quality_full.csv")
area_density_path = str(DATA_DIR / "Population_LandArea_Density_Province.csv")
station_province_path = str(DATA_DIR / "stations_city_province-stations.csv")


df_air_quality = pd.read_csv(air_quality_path)
df_area_density = pd.read_csv(area_density_path)
df_station_province = pd.read_csv(station_province_path)

## **Data Inspection**

In [3]:
print(df_air_quality.head(10))
print(df_area_density.head(10))
print(df_station_province.head(10))

     station  location_id  sensor_id parameter      lat       lon  \
0  313_Cubao      5963700   14249763       pm1  14.6227  121.0528
1  313_Cubao      5963700   14249763       pm1  14.6227  121.0528
2  313_Cubao      5963700   14249763       pm1  14.6227  121.0528
3  313_Cubao      5963700   14249763       pm1  14.6227  121.0528
4  313_Cubao      5963700   14249763       pm1  14.6227  121.0528
5  313_Cubao      5963700   14249763       pm1  14.6227  121.0528
6  313_Cubao      5963700   14249763       pm1  14.6227  121.0528
7  313_Cubao      5963700   14249763       pm1  14.6227  121.0528
8  313_Cubao      5963700   14249764      pm25  14.6227  121.0528
9  313_Cubao      5963700   14249764      pm25  14.6227  121.0528

                datetime_utc      value   unit
0  2025-09-30 07:00:00+00:00   9.001000  µg/m³
1  2025-09-30 22:00:00+00:00  34.000000  µg/m³
2  2025-09-30 23:00:00+00:00  27.805894  µg/m³
3  2025-10-01 00:00:00+00:00  20.776083  µg/m³
4  2025-10-01 01:00:00+00:00  20.805986  µg/m³
5  2025-10-01 02:00:00+00:00  11.475625  µg/m³
6  2025-10-01 03:00:00+00:00   3.681472  µg/m³
7  2025-10-01 04:00:00+00:00   0.000000  µg/m³
8  2025-09-30 07:00:00+00:00  19.652000  µg/m³
9  2025-09-30 22:00:00+00:00  52.500000  µg/m³
   Region and Province  Population Land area (sq. km.) a1/a2/a3  \
0                  NCR  14,001,751                       619.54
1                 Abra     246,948                     4,199.72
2              Apayao      126,587                     4,502.33
3            Benguet i     473,190                     2,769.08
4               Ifugao     208,668                     2,618.01
5            Kalinga       235,391                     3,282.04
6    Mountain Province     149,775                     2,389.43
7         Ilocos Norte     618,850                     3,418.75
8           Ilocos Sur     709,991                     2,596.00
9             La Union     825,072                     1,499.28

  Density (persons/ sq km)
0                   21,765
1                       60
2                       28
3                      166
4                       79
5                       70
6                       66
7                      178
8                      272
9                      548
                                     station       lat        lon  \
0                                  313_Cubao  14.62270  121.05280
1                        3S Center Bagbaguin  14.71405  121.00088
2                     3S Center Paso De Blas  14.71071  120.99545
3                            3S Center Ugong  14.69397  121.00919
4                       ADB Courtyard (Demo)  14.58828  121.05896
5                                      ASMPH  14.59083  121.07037
6                           Along Shaw Blvd.  14.57863  121.05675
7                                Anda Circle  14.59064  120.97112
8  Aurora Boulevard (Tramo) - Andrews Avenue  14.52904  121.00472
9                                 Ayala Ave.  14.55612  121.02236

          city province
0       Quezon      NCR
1   Valenzuela      NCR
2   Valenzuela      NCR
3   Valenzuela      NCR
4  Mandaluyong      NCR
5        Pasig      NCR
6  Mandaluyong      NCR
7       Manila      NCR
8        Pasay      NCR
9       Makati      NCR

In [4]:
for col in df_air_quality.columns:
    print(f'Unique values for {col}: {df_air_quality[col].unique()}')
    print("-" * 100)

Unique values for station: <ArrowStringArray>
[                                                                              '313_Cubao',
                                                                     '3S Center Bagbaguin',
                                                                  '3S Center Paso De Blas',
                                                                         '3S Center Ugong',
                                                                    'ADB Courtyard (Demo)',
                                                                                   'ASMPH',
                                                                        'Along Shaw Blvd.',
                                                                             'Anda Circle',
                                               'Aurora Boulevard (Tramo) - Andrews Avenue',
                                                                              'Ayala Ave.',
                                                                               'Ayala MRT',
                                                        'Bacolod City Araneta-Hernaez Sts',
                                                       'Bacolod City San Juan-Gonzaga Sts',
                                                       'Barangay Buli - Concepcion Street',
                                                        'Barangay Fortune - Santan Street',
                                  'Barangay San Antonio - Parañaque-Sucat Road (Shopwise)',
                                                                'Barangay San Rafael Hall',
                                                         'Barangay Tambo - Quirino Avenue',
                                                                   'Barangay Tanza 2 Hall',
                             'Barangay Tunasan - Maharlika Highway (SM Center Muntinlupa)',
                                                                     'Bataan Tourism Park',
                                                                              'Binangonan',
                                                            'Bo. Luz Barangay Hall, Limay',
                                                                            'Boni Serrano',
                                                               'Bradco Ave. cor Macapagal',
                                                                        'Brgy. Ambassador',
                                                           'Brgy. Benedicto, Jaro, Iloilo',
                                                                 'Brgy. East Timawa, Molo',
                                                                           'Brgy. Infante',
                                           'C3 Road (5th Avenue) - Rizal Avenue Extension',
                                                                 'Caloocan Sports Complex',
                                                           'Central Philippine University',
                                                                    'DENR Compound Parola',
                                                                             'DLSU Laguna',
                                                        'Daet, Camarines Norte (Roadside)',
                                                                             'Demo Unit 1',
                                                                             'Demo Unit 2',
                                                                             'Demo Unit 4',
                                                  'Gen. Luna St. corner Gov. Pascual Ave.',
                                                                                'Illumina',
                                                      'Iloilo City, Augustine Grove Subd.',
                                                          'J.P. Rizal Avenue corner Camia',
                                                      'J.P. Rizal Avenue corner Pertierra',
                                            'Kalayaan Avenue  - South Avenue Intersection',
                                                                            'Lamao, Limay',
                                                                          'Lapu-Lapu City',
                                                                               'Las Pinas',
                                                                         'MNHS AQ Station',
                                     'Makati Avenue  - Antonio Arnaiz Avenue Intersection',
                                             'Makati Avenue - Buendia Avenue Intersection',
                                                                   'Malabon Action Center',
                                                                     'Mall of Asia Sensor',
                                                                        'Mandaluyong City',
                                                           'Mandaluyong Elementary School',
                                                                                  'Manila',
                                                                      'Manila Observatory',
                                                                                'Marikina',
                                                                 'Marikina Sports Complex',
                                                                'Mariveles Municipal Hall',
                                                                     'Monumento, Caloocan',
                                                            'NASA GSFC Rutgers Calib. N12',
                                                        'Near Katipunan Ave., Quezon City',
                                                                   'Near Puregold Tayuman',
                                                             'Near Sucat Interchange/Exit',
 'North Caloocan Nova Romania - Alora (download airgradient mobile app for realtime data)',
                                                'Old Wack Wack Road corner Shaw Boulevard',
                                                                                 'Ortigas',
                                                   'Ortigas Avenue-Roosevelt Intersection',
                                                                           'Pasay Rotonda',
                                                                              'Pasay-Taft',
                                                                          'Pateros Bridge',
                                                                              'Pinya Farm',
                                                                         'President Roxas',
                                                                    'Quezon Rd, San Simon',
                                                                            'Quezon Road ',
                                                                     'Rajah Sulayman Park',
                                                              'Ramon Avancena High School',
                                                     'Robinson's Equitable Tower (Indoor)',
                                                                                    'STRC',
                                                                    'Samal Municipal Hall',
                                            'San Antonio, Los Banos, Laguna (Residential)',
                                                                      'San Juan Mini Park',
                                                                'San Sebastian Residences',
                                               'Santa Clara - Pasay City General Hospital',
                                                                                'Sensor 1',
                                                             'South Triangle, Quezon City',
                                                                       'Sta. Ana Hospital',
                                                                     'Sto. Rosario Bridge',
                                                                     'Tagaytay (Neogan 2)',
                                                                       'Tagaytay (Neogan)',
                                                     'Timoteo Paez Integrated High School',
                                                                                  'Tivoli',
                                                          'Unnamed (DNVBA1576 → AL739RG7)',
                                                                              'Valenzuela',
                                                           'Valenzuela CENRO (ARCA North)',
                                                                                  'Valle1',
                                                                      'World Trade Center',
                                                                              'pasay city']
Length: 98, dtype: str
----------------------------------------------------------------------------------------------------
Unique values for location_id: [5963700 4797652 4797660 4795497 6384709 4963739 3990425 6303936 4797649
 6393360 5974688 6484875 6484876 4797653 4797658 4797654 4795495 4797648
 4795500 4797656 4011497 3364093 4011496 3370072 4526989 4725233 3327567
 3336373 3337463 4797659 4797639 3004174 5359200 6521143 6416608 2812750
 3015284 3015283 4795496 6163209 2879671 4797637 4797645 4797640 4011498
 6455462 5976206 3771604 4797655 4797657 4795499 1845518 3370151 4797638
 1543132 4565934 6265529 4797647 4011499 4526987 3027756 4526988 6303935
 3990426 6230501 4797661 3015285 4797651 5995084 3370071 4797650 6375864
 6341180 2812740 5806034 6338564 6209259 6518181 4049149 4929685 6518182
 4797646 6303937 4797642 6519465 1846215 6303934 4797643 6443974 6343810
 6284033 6340868 4797641 5975180 4795498 6391974 4797644 6275863]
----------------------------------------------------------------------------------------------------
Unique values for sensor_id: [14249763 14249764 14249765 14249766 14249767 13372964 13372954 13370886
 16482922 13516723 12707934 15922106 13372961 16547006 14258133 14258134
 14258135 14258136 14258137 17218034 17218035 17218036 17218037 17218038
 17218039 17218040 17218041 17218042 17218043 13372967 13372953 13372948
 13370885 13372947 13370883 13372960 12746194 11990313 11990335 11990315
 11990319 11990345 11990343 12746196 12034966 13153270 13367544 13367545
 13367546 13367547 13367548 11727953 11727949 11727954 11727965 11727948
 11727936 11794638 11794647 11794652 11794662 11794675 11794676 11803309
 11803354 11803348 11803336 11803349 11803327 13372957 13372956 10171082
 10171089 10171080 10171091 10171090 10171107 17475140 17475141 17475142
 17475143 17475144 17484377 17484378 16718757 16718758 16718759 16718760
 16718761  8967443 10253231 10253229 13370884 14878556 14878557 14878558
 14878559 14878560  9466052  9466058  9466036  9466064  9466035  9466070
 13372946 13372950 13372965 12746193 17002975 14264525 14264526 14264527
 14264528 14264529 12530548 13372962 13372949 13370882  7411741  7411742
 12035571 13372963  6909373 13191002 13191003 13191004 13191005 13191006
 15636039 15636040 15636041 15636042 15636043 13372955 12746195 13153271
 10346948 13153272 15922109 12707936 15374904 15374905 15374906 15374907
 15374908 13372966 10253230 13372951 14272758 14272759 14272760 14272761
 14272762 12034965 13372959 16417805 16417806 16417807 16417808 16417809
 16200806 16200807 16200808 16200809 16200810  8966895 14130498 16181084
 15219514 15219515 15219516 15219517 15219518 17462565 17462566 17462567
 17462568 17462569 12775715 12775716 12775717 12775718 12775719 13488586
 17462570 17462571 17462572 17462573 17462574 13372945 15922107 13372952
 17472048 17472049 17472050 17472051 17472052  7412720  7412719 15922108
 13372944 16919124 16919125 16919126 16919127 16919128 16220566 16220567
 16220568 16220569 16220570 15772599 15772600 15772601 15772602 15772603
 16198442 16198443 16198444 16198445 16198446 13372958 14258420 14258421
 14258422 14258423 14258424 13370881 16536688 16536689 16536690 16536691
 16536692 13372968 15712747 15712748 15712749 15712750 15712751]
----------------------------------------------------------------------------------------------------
Unique values for parameter: <ArrowStringArray>
['pm1', 'pm25', 'relativehumidity', 'temperature', 'um003', 'pm10']
Length: 6, dtype: str
----------------------------------------------------------------------------------------------------
Unique values for lat: [14.6227     14.71405    14.71071    14.69397    14.58828    14.59083
 14.57863    14.59064    14.52904    14.55612    14.5496     10.6635921
 10.6694049  14.44481    14.66115    14.45671    14.63666    14.51769
 14.67508    14.37853    14.67759    14.5235999  14.5507     14.61071
 14.52917    16.49742018 10.7258204  10.696736   10.6941494  14.64443
 14.75097    10.73146968 10.69402521 14.26266    14.1157     14.58594
 15.0247     15.19384    14.66963     7.143752   10.73536978 14.56746
 14.56838    14.5688     14.515      10.32645    14.437546   10.99814
 14.56127    14.66916    14.536036   14.58455    14.58655    14.57711
 14.6354     14.65568    14.6341     14.436      14.65744    14.63525
 14.63842    14.61825    14.45627    14.7459495  14.58734    14.58853
 14.60346    14.53766    14.5377     14.5457     14.143177   11.43032
 15.00045    14.99976    14.569      14.593565   14.58944    14.56637518
 14.76944    14.17488    14.60399    14.59871    14.54848    14.639479
 14.58385    14.54939    14.098141   14.095018   14.630765   14.676664
 14.56383    14.688555   14.69158    14.576655   14.55157    14.558248  ]
----------------------------------------------------------------------------------------------------
Unique values for lon: [121.0528     121.00088    120.99545    121.00919    121.05896
 121.07037    121.05675    120.97112    121.00472    121.02236
 121.0285     122.9434386  122.9453514  121.04586    121.12476
 121.03519    120.96414    120.99638    120.93989    121.04615
 120.5182     121.1645249  120.5975     121.05484    120.98988
 120.6534127  122.5580665  122.5488203  122.5551708  120.98409
 121.02042    122.54695296 122.580963   121.04338    122.9551
 121.02932    120.68723    120.63862    120.94676    125.625054
 122.53702704 121.03929    121.02845    121.01795    120.609
 123.97871    121.000088   125.64968    121.02221    121.02799
 120.97576    120.985543   121.01877    121.02549    120.9778
 121.0779     121.11149    121.09803    120.4903     120.98362
 121.07784    121.0767     120.97142    121.04569    121.0101457
 121.04665    121.05822    121.04448    121.00039    121.00094
 121.06514    120.984941   122.926229   120.7505     120.75153
 120.98366    120.989459   121.05978    120.99223683 120.54278
 121.24649    121.02781    120.98947    121.00053    121.0827
 121.032469   121.01645    121.07264    120.892358   120.895382
 120.967483   121.095814   121.05797    120.970708   120.97246
 121.070464   120.98649    120.993386  ]
----------------------------------------------------------------------------------------------------
Unique values for datetime_utc: <ArrowStringArray>
['2025-09-30 07:00:00+00:00', '2025-09-30 22:00:00+00:00',
 '2025-09-30 23:00:00+00:00', '2025-10-01 00:00:00+00:00',
 '2025-10-01 01:00:00+00:00', '2025-10-01 02:00:00+00:00',
 '2025-10-01 03:00:00+00:00', '2025-10-01 04:00:00+00:00',
 '2025-06-19 18:01:39+00:00', '2025-06-19 18:18:38+00:00',
 ...
 '2026-03-07 17:15:30+00:00', '2026-03-07 17:33:20+00:00',
 '2026-03-07 17:51:09+00:00', '2026-03-07 18:08:59+00:00',
 '2026-03-07 18:26:45+00:00', '2026-03-07 18:44:31+00:00',
 '2026-03-07 19:02:20+00:00', '2026-03-07 19:20:10+00:00',
 '2026-03-07 19:37:56+00:00', '2026-03-07 19:55:43+00:00']
Length: 912848, dtype: str
----------------------------------------------------------------------------------------------------
Unique values for value: [  9.00099996  34.          27.80589379 ... 144.03       109.28
 127.03      ]
----------------------------------------------------------------------------------------------------
Unique values for unit: <ArrowStringArray>
['µg/m³', '%', 'c', 'particles/cm³']
Length: 4, dtype: str
----------------------------------------------------------------------------------------------------

In [5]:
for col in df_area_density.columns:
    print(f'Unique values for {col}: {df_area_density[col].unique()}')
    print("-" * 100)

Unique values for Region and Province: <ArrowStringArray>
[                                    'NCR',
                                   ' Abra',
                               '  Apayao ',
                             '  Benguet i',
                                '  Ifugao',
                             '  Kalinga  ',
                     '  Mountain Province',
                          '  Ilocos Norte',
                            '  Ilocos Sur',
                              '  La Union',
                            '  Pangasinan',
                               '  Batanes',
                               '  Cagayan',
                               '  Isabela',
                        '  Nueva Vizcaya ',
                               '  Quirino',
                               '  Aurora ',
                                '  Bataan',
                              '  Bulacan ',
                           '  Nueva Ecija',
                            '  Pampanga i',
                                '  Tarlac',
                            '  Zambales i',
                              '  Batangas',
                                '  Cavite',
                                '  Laguna',
                              '  Quezon i',
                                '  Rizal ',
                            '  Marinduque',
                    '  Occidental Mindoro',
                      '  Oriental Mindoro',
                             '  Palawan i',
                               '  Romblon',
                                 '  Albay',
                       '  Camarines Norte',
                         '  Camarines Sur',
                           '  Catanduanes',
                               '  Masbate',
                              '  Sorsogon',
                                 '  Aklan',
                               '  Antique',
                                 '  Capiz',
                            '  Guimaras  ',
                              '  Iloilo i',
                   'Negros Occidental 1,i',
            'Negros Island Region (NIR) 6',
                       'Negros Oriental 8',
                              'Siquijor 8',
                                 '  Bohol',
                                '  Cebu i',
                       'Negros Oriental 1',
                              '  Siquijor',
                             '  Biliran  ',
                         '  Eastern Samar',
                               '  Leyte i',
                        '  Northern Samar',
                 '  Samar (Western Samar)',
                        '  Southern Leyte',
                   '  Zamboanga del Norte',
                   '  Zamboanga del Sur i',
                     '  Zamboanga Sibugay',
                              '  Bukidnon',
                              '  Camiguin',
                     '  Lanao del Norte i',
                    '  Misamis Occidental',
                    '  Misamis Oriental i',
      'Davao De Oro (Compostela Valley) 2',
                       '  Davao del Norte',
                       '  Davao del Sur i',
                      '  Davao Occidental',
                        '  Davao Oriental',
        '  Cotabato (North Cotabato)     ',
                             '  Sarangani',
                      '  South Cotabato i',
                        '  Sultan Kudarat',
                    '  Agusan del Norte i',
                        '  Agusan del Sur',
                       '  Dinagat Islands',
                     '  Surigao del Norte',
                       '  Surigao del Sur',
   '  Basilan (excluding City of Isabela)',
                         '  Lanao del Sur',
 '  Maguindanao (excluding Cotabato City)',
                 'Maguindanao Del Norte 9',
                   'Maguindanao Del Sur 9',
                                  '  Sulu',
                             '  Tawi-Tawi']
Length: 87, dtype: str
----------------------------------------------------------------------------------------------------
Unique values for Population: <ArrowStringArray>
['14,001,751',    '246,948',    '126,587',    '473,190',    '208,668',
    '235,391',    '149,775',    '618,850',    '709,991',    '825,072',
  '3,188,540',     '18,937',  '1,284,676',  '1,733,048',    '530,106',
    '210,841',    '240,824',    '891,440',  '3,876,806',  '2,395,816',
  '2,586,446',  '1,568,162',    '681,225',  '2,994,795',  '4,573,884',
  '3,687,345',  '1,980,338',  '3,416,541',    '226,522',    '511,417',
    '919,504',    '968,795',    '302,824',  '1,379,398',    '604,666',
  '2,063,314',    '261,169',    '910,813',    '845,066',    '634,422',
    '643,173',    '835,098',    '192,874',  '2,082,616',  '2,680,477',
  '4,904,944',  '1,492,038',    '107,642',  '1,412,726',  '3,400,522',
          '…',    '184,095',    '472,683',  '1,823,458',    '645,789',
    '806,179',    '434,372',  '1,067,067',  '1,045,126',    '661,498',
  '1,601,902',     '94,892',    '761,725',    '621,993',    '988,065',
    '783,775',  '1,143,931',    '705,129',    '317,598',    '590,042',
  '1,286,142',    '580,915',  '1,010,009',    '863,651',    '404,100',
    '740,531',    '120,533',    '565,644',    '648,858',    '541,947',
  '1,368,137',  '1,124,811',    '813,243',  '1,146,097',    '482,645']
Length: 85, dtype: str
----------------------------------------------------------------------------------------------------
Unique values for Land area (sq. km.) a1/a2/a3: <ArrowStringArray>
[   '619.54',  '4,199.72',  '4,502.33',  '2,769.08',  '2,618.01',  '3,282.04',
  '2,389.43',  '3,418.75',  '2,596.00',  '1,499.28',  '5,450.59',    '203.22',
  '9,398.07', '13,102.05',  '4,813.88',  '2,319.66',  '3,133.40',  '1,372.98',
  '2,783.69',  '5,689.69',  '2,001.22',  '3,046.49',  '3,630.35',  '3,115.05',
  '1,526.28',  '1,928.23',  '8,743.84',  '1,182.65',    '952.58',  '5,851.09',
  '4,238.38', '14,649.73',  '1,533.45',  '2,574.91',  '2,277.93',  '5,511.90',
  '1,492.16',  '4,138.56',  '2,119.01',  '1,760.30',  '2,730.67',  '2,594.64',
    '611.87',  '4,997.64',  '7,844.12',         '…',  '4,772.52',  '4,943.72',
  '5,420.57',    '337.49',    '536.01',  '4,617.16',  '6,335.44',  '3,694.96',
  '6,048.03',  '1,801.46',  '7,300.11',  '4,484.21',  '3,481.28', '10,498.59',
    '241.44',  '3,354.16',  '2,006.63',  '3,131.52',  '4,560.09',  '3,422.61',
  '2,163.98',  '2,163.45',  '5,679.64',  '9,317.30',  '3,642.16',  '3,793.90',
  '5,363.86',  '2,611.63',  '9,989.52',    '817.47',  '1,952.62',  '4,932.70',
  '3,453.42', '15,055.51',  '9,968.31',  '4,547.16',  '3,626.55']
Length: 83, dtype: str
----------------------------------------------------------------------------------------------------
Unique values for Density (persons/ sq km): <ArrowStringArray>
['21,765',     '60',     '28',    '166',     '79',     '70',     '66',
    '178',    '272',    '548',    '580',     '93',    '135',    '130',
    '103',     '88',     '75',    '622',  '1,332',    '406',  '1,218',
    '494',    '179',    '934',  '2,847',  '1,754',    '223',  '2,816',
    '251',     '90',    '214',     '64',    '201',    '534',    '276',
    '375',    '182',    '220',    '391',    '350',    '224',    '310',
    '307',    '411',    '334',      '…',    '292',    '673',    '264',
    '306',    '335',    '280',    '173',    '131',    '238',    '143',
    '234',    '192',    '147',    '384',    '216',    '308',    '168',
    '329',    '314',    '101',    '160',    '153',    '257',    '159',
    '148',     '74',    '157',    '274',    '123',    '121']
Length: 76, dtype: str
----------------------------------------------------------------------------------------------------

In [6]:
for col in df_station_province.columns:
    print(f'Unique values for {col}: {df_station_province[col].unique()}')
    print("-" * 100)

Unique values for station: <ArrowStringArray>
[                                                                              '313_Cubao',
                                                                     '3S Center Bagbaguin',
                                                                  '3S Center Paso De Blas',
                                                                         '3S Center Ugong',
                                                                    'ADB Courtyard (Demo)',
                                                                                   'ASMPH',
                                                                        'Along Shaw Blvd.',
                                                                             'Anda Circle',
                                               'Aurora Boulevard (Tramo) - Andrews Avenue',
                                                                              'Ayala Ave.',
                                                                               'Ayala MRT',
                                                        'Bacolod City Araneta-Hernaez Sts',
                                                       'Bacolod City San Juan-Gonzaga Sts',
                                                       'Barangay Buli - Concepcion Street',
                                                        'Barangay Fortune - Santan Street',
                                  'Barangay San Antonio - Parañaque-Sucat Road (Shopwise)',
                                                                'Barangay San Rafael Hall',
                                                         'Barangay Tambo - Quirino Avenue',
                                                                   'Barangay Tanza 2 Hall',
                             'Barangay Tunasan - Maharlika Highway (SM Center Muntinlupa)',
                                                                     'Bataan Tourism Park',
                                                                              'Binangonan',
                                                            'Bo. Luz Barangay Hall, Limay',
                                                                            'Boni Serrano',
                                                               'Bradco Ave. cor Macapagal',
                                                                        'Brgy. Ambassador',
                                                           'Brgy. Benedicto, Jaro, Iloilo',
                                                                 'Brgy. East Timawa, Molo',
                                                                           'Brgy. Infante',
                                           'C3 Road (5th Avenue) - Rizal Avenue Extension',
                                                                 'Caloocan Sports Complex',
                                                           'Central Philippine University',
                                                                    'DENR Compound Parola',
                                                                             'DLSU Laguna',
                                                        'Daet, Camarines Norte (Roadside)',
                                                                             'Demo Unit 1',
                                                                             'Demo Unit 2',
                                                                             'Demo Unit 4',
                                                  'Gen. Luna St. corner Gov. Pascual Ave.',
                                                                                'Illumina',
                                                      'Iloilo City, Augustine Grove Subd.',
                                                          'J.P. Rizal Avenue corner Camia',
                                                      'J.P. Rizal Avenue corner Pertierra',
                                            'Kalayaan Avenue  - South Avenue Intersection',
                                                                            'Lamao, Limay',
                                                                          'Lapu-Lapu City',
                                                                               'Las Pinas',
                                                                         'MNHS AQ Station',
                                     'Makati Avenue  - Antonio Arnaiz Avenue Intersection',
                                             'Makati Avenue - Buendia Avenue Intersection',
                                                                   'Malabon Action Center',
                                                                     'Mall of Asia Sensor',
                                                                        'Mandaluyong City',
                                                           'Mandaluyong Elementary School',
                                                                                  'Manila',
                                                                      'Manila Observatory',
                                                                                'Marikina',
                                                                 'Marikina Sports Complex',
                                                                'Mariveles Municipal Hall',
                                                                     'Monumento, Caloocan',
                                                            'NASA GSFC Rutgers Calib. N12',
                                                        'Near Katipunan Ave., Quezon City',
                                                                   'Near Puregold Tayuman',
                                                             'Near Sucat Interchange/Exit',
 'North Caloocan Nova Romania - Alora (download airgradient mobile app for realtime data)',
                                                'Old Wack Wack Road corner Shaw Boulevard',
                                                                                 'Ortigas',
                                                   'Ortigas Avenue-Roosevelt Intersection',
                                                                           'Pasay Rotonda',
                                                                              'Pasay-Taft',
                                                                          'Pateros Bridge',
                                                                              'Pinya Farm',
                                                                         'President Roxas',
                                                                    'Quezon Rd, San Simon',
                                                                             'Quezon Road',
                                                                     'Rajah Sulayman Park',
                                                              'Ramon Avancena High School',
                                                     'Robinson's Equitable Tower (Indoor)',
                                                                                    'STRC',
                                                                    'Samal Municipal Hall',
                                            'San Antonio, Los Banos, Laguna (Residential)',
                                                                      'San Juan Mini Park',
                                                                'San Sebastian Residences',
                                               'Santa Clara - Pasay City General Hospital',
                                                                                'Sensor 1',
                                                             'South Triangle, Quezon City',
                                                                       'Sta. Ana Hospital',
                                                                     'Sto. Rosario Bridge',
                                                                     'Tagaytay (Neogan 2)',
                                                                       'Tagaytay (Neogan)',
                                                     'Timoteo Paez Integrated High School',
                                                                                  'Tivoli',
                                                          'Unnamed (DNVBA1576 → AL739RG7)',
                                                                              'Valenzuela',
                                                           'Valenzuela CENRO (ARCA North)',
                                                                                  'Valle1',
                                                                      'World Trade Center',
                                                                              'pasay city']
Length: 98, dtype: str
----------------------------------------------------------------------------------------------------
Unique values for lat: [14.6227     14.71405    14.71071    14.69397    14.58828    14.59083
 14.57863    14.59064    14.52904    14.55612    14.5496     10.6635921
 10.6694049  14.44481    14.66115    14.45671    14.63666    14.51769
 14.67508    14.37853    14.67759    14.5235999  14.5507     14.61071
 14.52917    16.49742018 10.7258204  10.696736   10.6941494  14.64443
 14.75097    10.73146968 10.69402521 14.26266    14.1157     14.58594
 15.0247     15.19384    14.66963     7.143752   10.73536978 14.56746
 14.56838    14.5688     14.515      10.32645    14.437546   10.99814
 14.56127    14.66916    14.536036   14.58455    14.58655    14.57711
 14.6354     14.65568    14.6341     14.436      14.65744    14.63525
 14.63842    14.61825    14.45627    14.7459495  14.58734    14.58853
 14.60346    14.53766    14.5377     14.5457     14.143177   11.43032
 15.00045    14.99976    14.569      14.593565   14.58944    14.56637518
 14.76944    14.17488    14.60399    14.59871    14.54848    14.639479
 14.58385    14.54939    14.098141   14.095018   14.630765   14.676664
 14.56383    14.688555   14.69158    14.576655   14.55157    14.558248  ]
----------------------------------------------------------------------------------------------------
Unique values for lon: [121.0528    121.00088   120.99545   121.00919   121.05896   121.07037
 121.05675   120.97112   121.00472   121.02236   121.0285    122.9434386
 122.9453514 121.04586   121.12476   121.03519   120.96414   120.99638
 120.93989   121.04615   120.5182    121.1645249 120.5975    121.05484
 120.98988   120.6534127 122.5580665 122.5488203 122.5551708 120.98409
 121.02042   122.546953  122.580963  121.04338   122.9551    121.02932
 120.68723   120.63862   120.94676   125.625054  122.537027  121.03929
 121.02845   121.01795   120.609     123.97871   121.000088  125.64968
 121.02221   121.02799   120.97576   120.985543  121.01877   121.02549
 120.9778    121.0779    121.11149   121.09803   120.4903    120.98362
 121.07784   121.0767    120.97142   121.04569   121.0101457 121.04665
 121.05822   121.04448   121.00039   121.00094   121.06514   120.984941
 122.926229  120.7505    120.75153   120.98366   120.989459  121.05978
 120.9922368 120.54278   121.24649   121.02781   120.98947   121.00053
 121.0827    121.032469  121.01645   121.07264   120.892358  120.895382
 120.967483  121.095814  121.05797   120.970708  120.97246   121.070464
 120.98649   120.993386 ]
----------------------------------------------------------------------------------------------------
Unique values for city: <ArrowStringArray>
[         'Quezon',      'Valenzuela',     'Mandaluyong',           'Pasig',
          'Manila',           'Pasay',          'Makati',         'Bacolod',
      'Muntinlupa',        'Marikina',       'Parañaque',         'Navotas',
         'Balanga',      'Binangonan',           'Limay',          'Tublay',
          'Iloilo',        'Caloocan',           'Biñan',            'Daet',
    'San Fernando',        'Magalang',         'Malabon',           'Davao',
       'Lapu-Lapu',       'Las Piñas',         'Guiuan ',       'Mariveles',
        'San Juan',          'Taguig',          'Silang', 'President Roxas',
       'San Simon',           'Samal',       'Los Baños',         'Pateros',
        'Tagaytay']
Length: 37, dtype: str
----------------------------------------------------------------------------------------------------
Unique values for province: <ArrowStringArray>
[              'NCR', 'Negros Occidental',            'Bataan',
             'Rizal',           'Benguet',            'Iloilo',
            'Laguna',   'Camarines Norte',          'Pampanga',
     'Davao del Sur',              'Cebu',     'Eastern Samar',
            'Cavite',             'Capiz']
Length: 14, dtype: str
----------------------------------------------------------------------------------------------------

In [7]:
print(df_air_quality.columns)
print(df_area_density.columns)
print(df_station_province.columns)

Index(['station', 'location_id', 'sensor_id', 'parameter', 'lat', 'lon',
       'datetime_utc', 'value', 'unit'],
      dtype='str')
Index(['Region and Province', 'Population', 'Land area (sq. km.) a1/a2/a3',
       'Density (persons/ sq km)'],
      dtype='str')
Index(['station', 'lat', 'lon', 'city', 'province'], dtype='str')

Problem 1:
Formatting of Provinces in `df_area_density` does not exactly match that of `df_station_province`

Implemented Solution for Problem 1:
1) Extract the necessary values needed in `df_stations_province`
2) Extract the equivalent values into a new file `df_area_density_prod`
3) Modify only `df_area_density_prod`
4) Merge into `Analytical Base Table`

## **Analytical Base Table**

In [8]:
province_list = df_station_province["province"].unique()
for province in province_list:
    province.strip()
print(province_list)

<ArrowStringArray>
[              'NCR', 'Negros Occidental',            'Bataan',
             'Rizal',           'Benguet',            'Iloilo',
            'Laguna',   'Camarines Norte',          'Pampanga',
     'Davao del Sur',              'Cebu',     'Eastern Samar',
            'Cavite',             'Capiz']
Length: 14, dtype: str

In [9]:
df_area_density_prod = df_area_density.copy()

df_area_density_prod['Region and Province'] = df_area_density_prod['Region and Province'].str.strip()
print(df_area_density_prod['Region and Province'].unique())

<ArrowStringArray>
[                                  'NCR',
                                  'Abra',
                                'Apayao',
                             'Benguet i',
                                'Ifugao',
                               'Kalinga',
                     'Mountain Province',
                          'Ilocos Norte',
                            'Ilocos Sur',
                              'La Union',
                            'Pangasinan',
                               'Batanes',
                               'Cagayan',
                               'Isabela',
                         'Nueva Vizcaya',
                               'Quirino',
                                'Aurora',
                                'Bataan',
                               'Bulacan',
                           'Nueva Ecija',
                            'Pampanga i',
                                'Tarlac',
                            'Zambales i',
                              'Batangas',
                                'Cavite',
                                'Laguna',
                              'Quezon i',
                                 'Rizal',
                            'Marinduque',
                    'Occidental Mindoro',
                      'Oriental Mindoro',
                             'Palawan i',
                               'Romblon',
                                 'Albay',
                       'Camarines Norte',
                         'Camarines Sur',
                           'Catanduanes',
                               'Masbate',
                              'Sorsogon',
                                 'Aklan',
                               'Antique',
                                 'Capiz',
                              'Guimaras',
                              'Iloilo i',
                 'Negros Occidental 1,i',
          'Negros Island Region (NIR) 6',
                     'Negros Oriental 8',
                            'Siquijor 8',
                                 'Bohol',
                                'Cebu i',
                     'Negros Oriental 1',
                              'Siquijor',
                               'Biliran',
                         'Eastern Samar',
                               'Leyte i',
                        'Northern Samar',
                 'Samar (Western Samar)',
                        'Southern Leyte',
                   'Zamboanga del Norte',
                   'Zamboanga del Sur i',
                     'Zamboanga Sibugay',
                              'Bukidnon',
                              'Camiguin',
                     'Lanao del Norte i',
                    'Misamis Occidental',
                    'Misamis Oriental i',
    'Davao De Oro (Compostela Valley) 2',
                       'Davao del Norte',
                       'Davao del Sur i',
                      'Davao Occidental',
                        'Davao Oriental',
             'Cotabato (North Cotabato)',
                             'Sarangani',
                      'South Cotabato i',
                        'Sultan Kudarat',
                    'Agusan del Norte i',
                        'Agusan del Sur',
                       'Dinagat Islands',
                     'Surigao del Norte',
                       'Surigao del Sur',
   'Basilan (excluding City of Isabela)',
                         'Lanao del Sur',
 'Maguindanao (excluding Cotabato City)',
               'Maguindanao Del Norte 9',
                 'Maguindanao Del Sur 9',
                                  'Sulu',
                             'Tawi-Tawi']
Length: 87, dtype: str

In [10]:
df_area_density_prod['Region and Province'] = (
    df_area_density_prod['Region and Province']
    .str.replace(r'\s*\([^)]*\)', '', regex=True)
    .str.replace(r'\s+[0-9,i]+$', '', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

print(df_area_density_prod['Region and Province'].unique())

<ArrowStringArray>
[                  'NCR',                  'Abra',                'Apayao',
               'Benguet',                'Ifugao',               'Kalinga',
     'Mountain Province',          'Ilocos Norte',            'Ilocos Sur',
              'La Union',            'Pangasinan',               'Batanes',
               'Cagayan',               'Isabela',         'Nueva Vizcaya',
               'Quirino',                'Aurora',                'Bataan',
               'Bulacan',           'Nueva Ecija',              'Pampanga',
                'Tarlac',              'Zambales',              'Batangas',
                'Cavite',                'Laguna',                'Quezon',
                 'Rizal',            'Marinduque',    'Occidental Mindoro',
      'Oriental Mindoro',               'Palawan',               'Romblon',
                 'Albay',       'Camarines Norte',         'Camarines Sur',
           'Catanduanes',               'Masbate',              'Sorsogon',
                 'Aklan',               'Antique',                 'Capiz',
              'Guimaras',                'Iloilo',     'Negros Occidental',
  'Negros Island Region',       'Negros Oriental',              'Siquijor',
                 'Bohol',                  'Cebu',               'Biliran',
         'Eastern Samar',                 'Leyte',        'Northern Samar',
                 'Samar',        'Southern Leyte',   'Zamboanga del Norte',
     'Zamboanga del Sur',     'Zamboanga Sibugay',              'Bukidnon',
              'Camiguin',       'Lanao del Norte',    'Misamis Occidental',
      'Misamis Oriental',          'Davao De Oro',       'Davao del Norte',
         'Davao del Sur',      'Davao Occidental',        'Davao Oriental',
              'Cotabato',             'Sarangani',        'South Cotabato',
        'Sultan Kudarat',      'Agusan del Norte',        'Agusan del Sur',
       'Dinagat Islands',     'Surigao del Norte',       'Surigao del Sur',
               'Basilan',         'Lanao del Sur',           'Maguindanao',
 'Maguindanao Del Norte',   'Maguindanao Del Sur',                  'Sulu',
             'Tawi-Tawi']
Length: 85, dtype: str

In [11]:
df_air_quality = df_air_quality[df_air_quality['parameter']=="pm25"].copy()

In [12]:
analytical_base_table = pd.merge( df_air_quality,
                                  df_station_province,
                                  on= 'station'
                                  )

analytical_base_table.rename(columns={'value': 'pm25 in µg/m^3'}, inplace=True)
analytical_base_table.drop(columns=['location_id',
                                    'sensor_id',
                                    'lon_x',
                                    'lat_y',
                                    'parameter',
                                    'unit'], inplace=True)

In [13]:
for col in analytical_base_table.columns:
    print(f'Unique values for {col}: {analytical_base_table[col].unique()}')
    print("-" * 100)

Unique values for station: <ArrowStringArray>
[                                                                              '313_Cubao',
                                                                     '3S Center Bagbaguin',
                                                                  '3S Center Paso De Blas',
                                                                         '3S Center Ugong',
                                                                    'ADB Courtyard (Demo)',
                                                                                   'ASMPH',
                                                                        'Along Shaw Blvd.',
                                                                             'Anda Circle',
                                               'Aurora Boulevard (Tramo) - Andrews Avenue',
                                                                              'Ayala Ave.',
                                                                               'Ayala MRT',
                                                        'Bacolod City Araneta-Hernaez Sts',
                                                       'Bacolod City San Juan-Gonzaga Sts',
                                                       'Barangay Buli - Concepcion Street',
                                                        'Barangay Fortune - Santan Street',
                                  'Barangay San Antonio - Parañaque-Sucat Road (Shopwise)',
                                                                'Barangay San Rafael Hall',
                                                         'Barangay Tambo - Quirino Avenue',
                                                                   'Barangay Tanza 2 Hall',
                             'Barangay Tunasan - Maharlika Highway (SM Center Muntinlupa)',
                                                                     'Bataan Tourism Park',
                                                                              'Binangonan',
                                                            'Bo. Luz Barangay Hall, Limay',
                                                                            'Boni Serrano',
                                                               'Bradco Ave. cor Macapagal',
                                                                        'Brgy. Ambassador',
                                                           'Brgy. Benedicto, Jaro, Iloilo',
                                                                 'Brgy. East Timawa, Molo',
                                                                           'Brgy. Infante',
                                           'C3 Road (5th Avenue) - Rizal Avenue Extension',
                                                                 'Caloocan Sports Complex',
                                                           'Central Philippine University',
                                                                    'DENR Compound Parola',
                                                                             'DLSU Laguna',
                                                        'Daet, Camarines Norte (Roadside)',
                                                                             'Demo Unit 1',
                                                                             'Demo Unit 2',
                                                                             'Demo Unit 4',
                                                  'Gen. Luna St. corner Gov. Pascual Ave.',
                                                                                'Illumina',
                                                      'Iloilo City, Augustine Grove Subd.',
                                                          'J.P. Rizal Avenue corner Camia',
                                                      'J.P. Rizal Avenue corner Pertierra',
                                            'Kalayaan Avenue  - South Avenue Intersection',
                                                                            'Lamao, Limay',
                                                                          'Lapu-Lapu City',
                                                                               'Las Pinas',
                                                                         'MNHS AQ Station',
                                     'Makati Avenue  - Antonio Arnaiz Avenue Intersection',
                                             'Makati Avenue - Buendia Avenue Intersection',
                                                                   'Malabon Action Center',
                                                                     'Mall of Asia Sensor',
                                                                        'Mandaluyong City',
                                                           'Mandaluyong Elementary School',
                                                                                  'Manila',
                                                                      'Manila Observatory',
                                                                                'Marikina',
                                                                 'Marikina Sports Complex',
                                                                'Mariveles Municipal Hall',
                                                                     'Monumento, Caloocan',
                                                            'NASA GSFC Rutgers Calib. N12',
                                                        'Near Katipunan Ave., Quezon City',
                                                                   'Near Puregold Tayuman',
                                                             'Near Sucat Interchange/Exit',
 'North Caloocan Nova Romania - Alora (download airgradient mobile app for realtime data)',
                                                'Old Wack Wack Road corner Shaw Boulevard',
                                                                                 'Ortigas',
                                                   'Ortigas Avenue-Roosevelt Intersection',
                                                                           'Pasay Rotonda',
                                                                              'Pasay-Taft',
                                                                          'Pateros Bridge',
                                                                              'Pinya Farm',
                                                                         'President Roxas',
                                                                    'Quezon Rd, San Simon',
                                                                     'Rajah Sulayman Park',
                                                              'Ramon Avancena High School',
                                                     'Robinson's Equitable Tower (Indoor)',
                                                                                    'STRC',
                                                                    'Samal Municipal Hall',
                                            'San Antonio, Los Banos, Laguna (Residential)',
                                                                      'San Juan Mini Park',
                                                                'San Sebastian Residences',
                                               'Santa Clara - Pasay City General Hospital',
                                                                                'Sensor 1',
                                                             'South Triangle, Quezon City',
                                                                       'Sta. Ana Hospital',
                                                                     'Sto. Rosario Bridge',
                                                                     'Tagaytay (Neogan 2)',
                                                                       'Tagaytay (Neogan)',
                                                     'Timoteo Paez Integrated High School',
                                                                                  'Tivoli',
                                                          'Unnamed (DNVBA1576 → AL739RG7)',
                                                                              'Valenzuela',
                                                           'Valenzuela CENRO (ARCA North)',
                                                                                  'Valle1',
                                                                      'World Trade Center',
                                                                              'pasay city']
Length: 97, dtype: str
----------------------------------------------------------------------------------------------------
Unique values for lat_x: [14.6227     14.71405    14.71071    14.69397    14.58828    14.59083
 14.57863    14.59064    14.52904    14.55612    14.5496     10.6635921
 10.6694049  14.44481    14.66115    14.45671    14.63666    14.51769
 14.67508    14.37853    14.67759    14.5235999  14.5507     14.61071
 14.52917    16.49742018 10.7258204  10.696736   10.6941494  14.64443
 14.75097    10.73146968 10.69402521 14.26266    14.1157     14.58594
 15.0247     15.19384    14.66963     7.143752   10.73536978 14.56746
 14.56838    14.5688     14.515      10.32645    14.437546   10.99814
 14.56127    14.66916    14.536036   14.58455    14.58655    14.57711
 14.6354     14.65568    14.6341     14.436      14.65744    14.63525
 14.63842    14.61825    14.45627    14.7459495  14.58734    14.58853
 14.60346    14.53766    14.5377     14.5457     14.143177   11.43032
 15.00045    14.569      14.593565   14.58944    14.56637518 14.76944
 14.17488    14.60399    14.59871    14.54848    14.639479   14.58385
 14.54939    14.098141   14.095018   14.630765   14.676664   14.56383
 14.688555   14.69158    14.576655   14.55157    14.558248  ]
----------------------------------------------------------------------------------------------------
Unique values for datetime_utc: <ArrowStringArray>
['2025-09-30 07:00:00+00:00', '2025-09-30 22:00:00+00:00',
 '2025-09-30 23:00:00+00:00', '2025-10-01 00:00:00+00:00',
 '2025-10-01 01:00:00+00:00', '2025-10-01 02:00:00+00:00',
 '2025-10-01 03:00:00+00:00', '2025-10-01 04:00:00+00:00',
 '2025-06-19 18:01:39+00:00', '2025-06-19 18:18:38+00:00',
 ...
 '2026-03-07 17:15:30+00:00', '2026-03-07 17:33:20+00:00',
 '2026-03-07 17:51:09+00:00', '2026-03-07 18:08:59+00:00',
 '2026-03-07 18:26:45+00:00', '2026-03-07 18:44:31+00:00',
 '2026-03-07 19:02:20+00:00', '2026-03-07 19:20:10+00:00',
 '2026-03-07 19:37:56+00:00', '2026-03-07 19:55:43+00:00']
Length: 897758, dtype: str
----------------------------------------------------------------------------------------------------
Unique values for pm25 in µg/m^3: [ 19.65199998  52.5         41.96568121 ... 144.03       109.28
 127.03      ]
----------------------------------------------------------------------------------------------------
Unique values for lon_y: [121.0528    121.00088   120.99545   121.00919   121.05896   121.07037
 121.05675   120.97112   121.00472   121.02236   121.0285    122.9434386
 122.9453514 121.04586   121.12476   121.03519   120.96414   120.99638
 120.93989   121.04615   120.5182    121.1645249 120.5975    121.05484
 120.98988   120.6534127 122.5580665 122.5488203 122.5551708 120.98409
 121.02042   122.546953  122.580963  121.04338   122.9551    121.02932
 120.68723   120.63862   120.94676   125.625054  122.537027  121.03929
 121.02845   121.01795   120.609     123.97871   121.000088  125.64968
 121.02221   121.02799   120.97576   120.985543  121.01877   121.02549
 120.9778    121.0779    121.11149   121.09803   120.4903    120.98362
 121.07784   121.0767    120.97142   121.04569   121.0101457 121.04665
 121.05822   121.04448   121.00039   121.00094   121.06514   120.984941
 122.926229  120.7505    120.98366   120.989459  121.05978   120.9922368
 120.54278   121.24649   121.02781   120.98947   121.00053   121.0827
 121.032469  121.01645   121.07264   120.892358  120.895382  120.967483
 121.095814  121.05797   120.970708  120.97246   121.070464  120.98649
 120.993386 ]
----------------------------------------------------------------------------------------------------
Unique values for city: <ArrowStringArray>
[         'Quezon',      'Valenzuela',     'Mandaluyong',           'Pasig',
          'Manila',           'Pasay',          'Makati',         'Bacolod',
      'Muntinlupa',        'Marikina',       'Parañaque',         'Navotas',
         'Balanga',      'Binangonan',           'Limay',          'Tublay',
          'Iloilo',        'Caloocan',           'Biñan',            'Daet',
    'San Fernando',        'Magalang',         'Malabon',           'Davao',
       'Lapu-Lapu',       'Las Piñas',         'Guiuan ',       'Mariveles',
        'San Juan',          'Taguig',          'Silang', 'President Roxas',
       'San Simon',           'Samal',       'Los Baños',         'Pateros',
        'Tagaytay']
Length: 37, dtype: str
----------------------------------------------------------------------------------------------------
Unique values for province: <ArrowStringArray>
[              'NCR', 'Negros Occidental',            'Bataan',
             'Rizal',           'Benguet',            'Iloilo',
            'Laguna',   'Camarines Norte',          'Pampanga',
     'Davao del Sur',              'Cebu',     'Eastern Samar',
            'Cavite',             'Capiz']
Length: 14, dtype: str
----------------------------------------------------------------------------------------------------

In [14]:
analytical_base_table = pd.merge(analytical_base_table,
                                 df_area_density_prod,
                                 left_on = 'province',
                                 right_on =  'Region and Province',
                                 )

analytical_base_table.drop(columns=['Region and Province'], inplace=True)
analytical_base_table.rename(columns={'Land area (sq. km.) a1/a2/a3': 'area_in_sq.km', 'Density (persons/ sq km)': 'density_persons/sqkm', 'Population': 'population', 'lat_x': 'lat', 'lon_y': 'lon' }, inplace=True)

In [15]:
print(analytical_base_table.columns
      )
print(analytical_base_table.head(10))

Index(['station', 'lat', 'datetime_utc', 'pm25 in µg/m^3', 'lon', 'city',
       'province', 'population', 'area_in_sq.km', 'density_persons/sqkm'],
      dtype='str')
               station       lat               datetime_utc  pm25 in µg/m^3  \
0            313_Cubao  14.62270  2025-09-30 07:00:00+00:00       19.652000
1            313_Cubao  14.62270  2025-09-30 22:00:00+00:00       52.500000
2            313_Cubao  14.62270  2025-09-30 23:00:00+00:00       41.965681
3            313_Cubao  14.62270  2025-10-01 00:00:00+00:00       30.948667
4            313_Cubao  14.62270  2025-10-01 01:00:00+00:00       30.113639
5            313_Cubao  14.62270  2025-10-01 02:00:00+00:00       21.787083
6            313_Cubao  14.62270  2025-10-01 03:00:00+00:00        7.477500
7            313_Cubao  14.62270  2025-10-01 04:00:00+00:00        0.033333
8  3S Center Bagbaguin  14.71405  2025-06-19 18:01:39+00:00       11.120000
9  3S Center Bagbaguin  14.71405  2025-06-19 18:18:38+00:00       14.860000

         lon        city province  population area_in_sq.km  \
0  121.05280      Quezon      NCR  14,001,751        619.54
1  121.05280      Quezon      NCR  14,001,751        619.54
2  121.05280      Quezon      NCR  14,001,751        619.54
3  121.05280      Quezon      NCR  14,001,751        619.54
4  121.05280      Quezon      NCR  14,001,751        619.54
5  121.05280      Quezon      NCR  14,001,751        619.54
6  121.05280      Quezon      NCR  14,001,751        619.54
7  121.05280      Quezon      NCR  14,001,751        619.54
8  121.00088  Valenzuela      NCR  14,001,751        619.54
9  121.00088  Valenzuela      NCR  14,001,751        619.54

  density_persons/sqkm
0               21,765
1               21,765
2               21,765
3               21,765
4               21,765
5               21,765
6               21,765
7               21,765
8               21,765
9               21,765

In [16]:
analytical_base_table.to_csv(str(DATA_DIR / "Group2_ABT.csv"), index=False)

In [17]:
analytical_base_table.to_parquet(str(DATA_DIR / "Group2_ABT.parquet"), index=False)

---
## Descriptive Profile of the Analytical Base Table

The cells below are from `ABT_Descriptive.ipynb`. They originally re-read
the table from `Group2_ABT.csv` / `.parquet` on disk -- a different filename
than what the build section above actually produces
(`analytical_base_table.csv` / `.parquet`). Since this is now one notebook
in one kernel, we just alias the table already in memory instead:

In [18]:
import numpy as np  # NB2 also needs this; pandas and Path are already imported above

abt = analytical_base_table  # use the table just built, instead of re-reading a different file from disk

## **Null Statistics**

In [19]:
null_counts = abt.isnull().sum()
null_percent = (abt.isnull().sum() / len(abt)) * 100

null_stats = pd.DataFrame(
    {
        "Feature": abt.columns,
        "Null Count": null_counts.values,
        "Null Percentage (%)": null_percent.round(2).values,
    }
).sort_values(by="Null Count", ascending=False)

print("Null Statistics")
null_stats

Null Statistics

                Feature  Null Count  Null Percentage (%)
0               station           0                  0.0
1                   lat           0                  0.0
2          datetime_utc           0                  0.0
3        pm25 in µg/m^3           0                  0.0
4                   lon           0                  0.0
5                  city           0                  0.0
6              province           0                  0.0
7            population           0                  0.0
8         area_in_sq.km           0                  0.0
9  density_persons/sqkm           0                  0.0

## **Numerical Feature Statistics**

In [20]:
numeric_stats = abt.describe(include=[np.number],percentiles=[0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95]).T
print("\nNumerical Feature Statistics")
numeric_stats

Numerical Feature Statistics

,count,mean,std,min,5%,10%,25%,50%,75%,90%,95%,max
lat,1027171.0,14.297758,1.167600,7.143752,10.73537,14.37853,14.54570,14.58455,14.64443,14.71405,14.769440,16.49742
pm25 in µg/m^3,1027171.0,19.414052,28.260038,0.000000,2.03000,3.87000,7.80000,14.80000,24.08000,34.28000,44.089866,987.89000
lon,1027171.0,121.167812,0.778866,120.490300,120.59750,120.75050,120.98362,121.01877,121.05675,121.09803,122.548820,125.64968

## **Categorical Feature Statistics**

In [21]:
categorical_stats = abt.describe(include=["object", "category", "str"]).T
print("\nCategorical Feature Statistics")
categorical_stats

Categorical Feature Statistics

                        count  unique                        top    freq
station               1027171      97        3S Center Bagbaguin   17000
datetime_utc          1027171  897758  2026-09-04 01:00:00+00:00      20
city                  1027171      37                     Manila  103551
province              1027171      14                        NCR  821222
population            1027171      14                 14,001,751  821222
area_in_sq.km         1027171      14                     619.54  821222
density_persons/sqkm  1027171      14                     21,765  821222

## **Grouped Statistics by Province**

In [22]:
percentiles = [0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
quantile_funcs = [
    (f"p{int(p*100):02d}", (lambda q: lambda x: x.quantile(q))(p))
    for p in percentiles
]

print("\nGrouped Statistics by Province")
grouped_stats = abt.groupby("province")[["lat", "lon", "pm25 in µg/m^3"]].agg(["mean","min","max"] + quantile_funcs).T
grouped_stats

Grouped Statistics by Province

province                 Bataan     Benguet  Camarines Norte       Capiz  \
lat            mean   14.625148   16.497420        14.115700   11.430320
               min    14.436000   16.497420        14.115700   11.430320
               max    14.769440   16.497420        14.115700   11.430320
               p05    14.515000   16.497420        14.115700   11.430320
               p10    14.515000   16.497420        14.115700   11.430320
               p25    14.515000   16.497420        14.115700   11.430320
               p50    14.550700   16.497420        14.115700   11.430320
               p75    14.677590   16.497420        14.115700   11.430320
               p90    14.769440   16.497420        14.115700   11.430320
               p95    14.769440   16.497420        14.115700   11.430320
lon            mean  120.565661  120.653413       122.955100  122.926229
               min   120.490300  120.653413       122.955100  122.926229
               max   120.609000  120.653413       122.955100  122.926229
               p05   120.518200  120.653413       122.955100  122.926229
               p10   120.518200  120.653413       122.955100  122.926229
               p25   120.518200  120.653413       122.955100  122.926229
               p50   120.542780  120.653413       122.955100  122.926229
               p75   120.597500  120.653413       122.955100  122.926229
               p90   120.609000  120.653413       122.955100  122.926229
               p95   120.609000  120.653413       122.955100  122.926229
pm25 in µg/m^3 mean   10.622870   16.794275        31.434669   32.040528
               min     0.000000    0.000000         0.100000    0.000000
               max   144.970000  858.000000       125.700000  537.100000
               p05     1.470000    0.100000         8.090000    2.300000
               p10     2.550000    0.500000        11.500000    4.600000
               p25     5.110000    2.640719        22.450000   12.000000
               p50     8.840000    9.245312        31.400000   24.700000
               p75    13.780000   25.800000        37.950000   38.300000
               p90    20.290000   41.770967        44.720000   61.200000
               p95    25.970000   51.400000        53.940000   88.875000

province                 Cavite        Cebu  Davao del Sur  Eastern Samar  \
lat            mean   14.143177   10.326450       7.143752      10.998140
               min    14.143177   10.326450       7.143752      10.998140
               max    14.143177   10.326450       7.143752      10.998140
               p05    14.143177   10.326450       7.143752      10.998140
               p10    14.143177   10.326450       7.143752      10.998140
               p25    14.143177   10.326450       7.143752      10.998140
               p50    14.143177   10.326450       7.143752      10.998140
               p75    14.143177   10.326450       7.143752      10.998140
               p90    14.143177   10.326450       7.143752      10.998140
               p95    14.143177   10.326450       7.143752      10.998140
lon            mean  120.984941  123.978710     125.625054     125.649680
               min   120.984941  123.978710     125.625054     125.649680
               max   120.984941  123.978710     125.625054     125.649680
               p05   120.984941  123.978710     125.625054     125.649680
               p10   120.984941  123.978710     125.625054     125.649680
               p25   120.984941  123.978710     125.625054     125.649680
               p50   120.984941  123.978710     125.625054     125.649680
               p75   120.984941  123.978710     125.625054     125.649680
               p90   120.984941  123.978710     125.625054     125.649680
               p95   120.984941  123.978710     125.625054     125.649680
pm25 in µg/m^3 mean   16.118440   30.494368      16.362142       5.084836
               min     0.000000    2.260000       0.000000       0.000000
               max   127.400000   68.620000     301.000000     909.220000
               p05     0.000000    6.127500       0.400000       1.200000
               p10     0.100000   10.250000       1.300000       1.570000
               p25     2.100000   18.645000       4.100000       2.170000
               p50    10.200000   32.460000      11.800000       3.070000
               p75    26.300000   39.032500      25.400000       5.035000
               p90    39.140000   47.805000      36.190000       8.840000
               p95    46.720000   52.637500      42.700000      11.742000

province                 Iloilo      Laguna         NCR  Negros Occidental  \
lat            mean   10.724084   14.198654   14.589308          10.664885
               min    10.694025   14.174880   14.095018          10.663592
               max    10.735370   14.262660   14.750970          10.669405
               p05    10.694149   14.174880   14.444810          10.663592
               p10    10.694149   14.174880   14.517690          10.663592
               p25    10.725820   14.174880   14.550700          10.663592
               p50    10.731470   14.174880   14.586550          10.663592
               p75    10.735370   14.262660   14.638420          10.663592
               p90    10.735370   14.262660   14.691580          10.669405
               p95    10.735370   14.262660   14.710710          10.669405
lon            mean  122.548410  121.191481  121.021059         122.943864
               min   122.537027  121.043380  120.892358         122.943439
               max   122.580963  121.246490  121.124760         122.945351
               p05   122.537027  121.043380  120.964140         122.943439
               p10   122.537027  121.043380  120.972460         122.943439
               p25   122.537027  121.043380  120.989880         122.943439
               p50   122.546953  121.246490  121.020420         122.943439
               p75   122.555171  121.246490  121.046150         122.943439
               p90   122.558066  121.246490  121.072640         122.945351
               p95   122.558066  121.246490  121.077900         122.945351
pm25 in µg/m^3 mean   22.940871   16.097917   17.766206          40.906861
               min     0.047917    0.000000    0.000000           6.600000
               max   987.800000   34.700000  987.890000          95.700000
               p05     3.869792    0.000000    2.250000          20.600000
               p10     5.600000    0.550000    4.340000          25.900000
               p25    10.663691    6.375000    8.270000          33.900000
               p50    19.900992   18.550000   15.370000          39.100000
               p75    32.114286   25.650000   23.990000          47.600000
               p90    43.108929   28.850000   32.800000          58.000000
               p95    49.877262   30.600000   41.100000          64.100000

province               Pampanga       Rizal
lat            mean   15.044728   14.523600
               min    15.000450   14.523600
               max    15.193840   14.523600
               p05    15.000450   14.523600
               p10    15.000450   14.523600
               p25    15.000450   14.523600
               p50    15.024700   14.523600
               p75    15.024700   14.523600
               p90    15.193840   14.523600
               p95    15.193840   14.523600
lon            mean  120.703970  121.164525
               min   120.638620  121.164525
               max   120.750500  121.164525
               p05   120.638620  121.164525
               p10   120.638620  121.164525
               p25   120.687230  121.164525
               p50   120.687230  121.164525
               p75   120.750500  121.164525
               p90   120.750500  121.164525
               p95   120.750500  121.164525
pm25 in µg/m^3 mean   69.068703   16.623882
               min     0.000000    0.152833
               max   972.590000  170.403962
               p05     4.630000    2.119431
               p10     6.250000    3.271625
               p25    11.030000    6.469917
               p50    21.050000   12.537000
               p75    52.292500   23.105292
               p90   240.833000   35.647150
               p95   345.434000   43.027812

## **Unique Values for Province**

In [23]:
abt["province"].unique()

<ArrowStringArray>
[              'NCR', 'Negros Occidental',            'Bataan',
             'Rizal',           'Benguet',            'Iloilo',
            'Laguna',   'Camarines Norte',          'Pampanga',
     'Davao del Sur',              'Cebu',     'Eastern Samar',
            'Cavite',             'Capiz']
Length: 14, dtype: str

# Initial Observations and Notable Findings

1. An overwhelming majority of sensors are located within the NCR province.
2. Only stations in Negros Oriental province provide pm10 data, thus it was excluded due to the limited number of observations.
3. Not all Philippine provinces are represented by air quality stations, a total of 14 provinces have coverage for air quality indicators.
4. Some stations have inconsistent reporting periods.